version: '3'

volumes:
  mongo_data:
      driver: local

services:
  mongo-express:
    image: mongo-express
    volumes:
      - mongo_data:/var/lib/mongodb/data
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: Admin2020!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: AdminAdmin2020!
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AdminAdmin2020!
    ports:
      - 27017:27017
    networks:
      - mongo-network

networks: 
    mongo-network:
      driver: bridge